
// This file was auto-generated by the shadcn CLI.
// It's is kept for backward compatibility but you should move to "sonner" instead.

import { useToast as useToastHook, toast } from "@/components/ui/toast"

export const useToast = useToastHook
export { toast }
