// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woxosvmnhouhbnwgiggn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndveG9zdm1uaG91aGJud2dpZ2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTcxMzIsImV4cCI6MjA1NDA5MzEzMn0.xtDnkVU4KSjpFbzVNd48QCbjTXo3sYhWrak93aeN-Eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);